SashaGordin/Carefinder

- client/src/components/LandingPage.js
> changed navbar to black

- client/src/components/CPLandingPage.js
> changed color to blackmade a change - color

- client/src/components/CPLandingPage.js
- client/src/components/LandingPage.js
> back to black

- server/server.js
> changed path to dotenv file to use Twilio variables in server

- client/src/components/App.js
- client/src/components/CPDashboard.js
- client/src/components/CPLandingPage.js
- client/src/components/ClaimProfile.js
- client/src/components/ClaimProfile/Step4.js
- client/src/components/ClaimProfile/Step5.js
- client/src/components/ClientDashboard.js
- client/src/components/Login.js
- client/src/components/PrivateRoute.js
- client/src/components/Signup.js
- client/src/contexts/AuthContext.js
- package.json
> finished the logic for provider sign up flow, added private routing, and client/ provider dashboards

- client/src/components/Footer.js
- client/src/components/LandingPage.js
- client/src/css/carefinder.css
basic CSS for client langing area, to be integrated in w/ google maps (did not yet add any styling for google maps results/data)
--added link to footer area for possible inclusion later for support chat, as in mica's wireframe
> basic CSS for client landing page (not incl. maps)

- client/src/components/CPLandingPage.js
just added micah's FAQs to the CPlandingPage.js file
> saving micah's faq list to CPlanding page

- client/src/components/App.js
- client/src/components/CareFinderContactUs.js
- client/src/components/CareFinderJoinTeam.js
- client/src/components/CareFinderPrivacy.js
- client/src/components/CareFinderSitemap.js
- client/src/components/CareFinderTerms.js
- client/src/components/ClaimProfile/Step1.js
- client/src/components/ClaimProfile/Step2.js
- client/src/components/ClaimProfile/Step3.js
- client/src/components/ClaimProfile/Step4.js
- client/src/components/ClaimProfile/Step5.js
- client/src/components/Footer.js
- client/src/components/ForgotPassword.js
- client/src/components/Login.js
- client/src/components/Signup.js
- client/src/components/SupportConnectAdvisor.js
- client/src/components/SupportReportIssue.js
- client/src/components/SupportSuggestion.js
- client/src/components/TopNav.js
- client/src/css/carefinder.css
added a sample bootstrap menu, but will need to customize with whatever the links need to say or go to. Added footer pages that did not exist -- micah will need to add some text in places. Added various CSS tweaks here and there.
> add menu template, add footer and admin apges, add CSS in various places

- client/public/index.html
- client/src/components/App.js
- client/src/components/MsgInbox.js
- client/src/components/MsgTemplate.js
- client/src/css/carefinder.css
some initial work on messaging, which will eventually be rolled out for clients, providers, and admins... can view messages, mark as read, mark as archived, send replies, etc. I need to do some "indexing" work on Firebase to get some sorting to work. And more coding, but this is a good beginning point to push and then will continue.
> initial work on messaging

- client/src/components/App.js
- client/src/components/CPDashboard.js
- client/src/components/CPListings.js
- client/src/components/TopNav.js
updated topnav to accept a property of userRole that determines the nav display and defaults to userRole="client" if none specified
> updated topnav to handle both user roles

- client/src/components/MsgInbox.js
- client/src/components/MsgTemplateMVP.js
- client/src/components/MsgThread.js
- client/src/css/carefinder.css
added conversation-style threads to the inbox functionality. Works pretty well throughout, with the minor exception of I'll still need to tweak the auto-scrolling, if possible, on mobile devices.  Other than that, seems to work really nicely.
> added threaded-style conversations to the inbox

- client/src/components/CPListings.js
- client/src/components/CPListings/ListingCard.js
- client/src/components/CPListings/RoomCard.js
- client/src/components/MsgTemplateMVP.js
- client/src/components/menu/EditableField.js
- client/src/components/menu/PersonalInfo.js
- client/src/css/carefinder.css
Added CSS to about 6 files in the CP listings area.
> css work on provider listings

- client/src/components/App.js
- client/src/components/MsgInbox.js
- client/src/components/MsgTemplateMVP.js
- client/src/components/MsgThread.js
- client/src/components/TopNav.js
- client/src/contexts/AuthContext.js
- client/src/css/carefinder.css
- client/src/pages/MessageAdmin.js
CSS updates (many more needed), inbox UX fix (no pageload on update -- behaves like a chat app now), added outbox so admins can mail out to users (basic, but works), other small tweaks
> Misc CSS and mail updates

- client/src/components/App.js
- client/src/components/TopNav.js
- client/src/css/carefinder.css
- client/src/pages/MsgOutbox.js
Outbound messaging page... Just link any button or link to: /msg-outbox?ref=[userID]  ... and you'll get a page to send that user a message.  Must pass a valid userID, and you cannot message yourself. Otherwise, behaves as expected.
> add outbox that takes a ref param

- client/src/components/App.js
- client/src/pages/CPHomeSurvey.js
- client/src/pages/CPListings.js
- client/src/pages/CPRoomSurvey.js
moved provider pages into the pages folder
minor update but wanted to get it out asap to avoid bad conflicts.
> separated pages/components for provider side

- client/src/pages/LandingPage.js
- server/server.js
added two endpoints in server.js as well as a test button on LandingPage.js to return listings with avail rooms. Everything is logged to console, so to test what data is returned you just click the button and check the console.
> added endpoints to query listings with available rooms

- client/src/components/App.js
- client/src/components/PrivateRoute.js
- client/src/pages/Login.js
- client/src/pages/Signup.js
- client/src/pages/VerifyEmail.js
Not sure if old accounts work (mine does), but from now on, all signups must verify their email addresses.
> add email verification requirement

- client/src/components/Footer.js
- client/src/components/PropertyPhotoModal.js
- client/src/components/ProviderCard.js
- client/src/components/ProviderProfileCard.js
- client/src/components/ReserveRoom/Step1.js
- client/src/components/VisitingMap.js
- client/src/components/zTempNotes.txt
- client/src/css/carefinder.css
- client/src/pages/ClientDashboard.js
- client/src/pages/LandingPage.js
- client/src/pages/Reservation/ReserveRoom.js
more css, to come, but quite a lot new here. Mainly, I wanted to push this now so that we can deploy a live version for Micah to review.  Will deploy to a live staging site once this and Sasha's next PR is merged into main.
> misc CSS updates and new home page - to be refined still

- client/src/components/TopNav-bak.js
- client/src/components/TopNav.js
- client/src/css/carefinder.css
- client/src/pages/ClientDashboard.js
misc css fixes, some various refactoring, added loading effect, mobile still tbd once micah reviews.
> redid menu -- mobile tbd once micah reviews

- client/src/components/CPListings/CPHomeSurvey/Step6.js
- client/src/components/CPListings/CPRoomSurvey/Step3.js
- client/src/components/CPListings/ListingCard.js
- client/src/components/CPListings/Profile.js
- client/src/components/DynamicModal.js
still needs styling, but functionality is there
> added pdf view modal and ability to delete photos/docs to provider side

- client/src/components/CareFinderContactUs.js
- client/src/components/MsgInbox.js
- client/src/components/MsgTemplateMVP.js
- client/src/components/SupportReportIssue.js
- client/src/components/SupportSuggestion.js
- client/src/components/TopNav.js
- client/src/pages/CPLandingPage.js
- client/src/pages/ClientDashboard.js
- client/src/pages/LandingPage.js
new changes to fix issues that crept into last main merge
> quick fixes to previous merge

- client/src/components/CPListings/AssociatedCoCNotIncluded.js
- client/src/components/CPListings/CostOfCare.js
- client/src/components/CPListings/ListingCard.js
- client/src/constants.js
- client/src/css/carefinder.css
- client/src/pages/CPRoomEdit.js
- client/src/pages/CPSelectGreeting.js
Added all the text for the different features and services, care descriptions, etc..
There's an annoying bug that I couldn't figure out that scrolls the list to the middle when clicking the buttons in HighlightedFeatures or CareNotIncluded. 
View Profile button on Listing Card is broken. Have to figure out what data is needed to pass in to ViewProfile.js component
> finished options for most of listing card

- client/src/components/ProviderCard.js
- client/src/components/ProviderProfileCard.js
- client/src/css/carefinder.css
- client/src/pages/ClientDashboard.js
some design tweaks from Micah. Changed up the ProfileCard and ProviderProfile card a good bit w/ respect to modals. But functions pretty much the same.
> misc changes from Micah

- .eslintrc.js
- .prettierrc
- client/src/components/CPListings/ListingCard.js
- client/src/components/CPListings/PersonalInfo.js
- client/src/components/ClientSurvey/SurveyAddress.js
- client/src/components/ClientSurvey/SurveyFinal.js
- client/src/components/ClientSurvey/SurveyInfo.js
- client/src/components/ClientSurvey/SurveyQuestionRadio.js
- client/src/components/TopNav.js
- client/src/components/menu/EditableField.js
- client/src/css/carefinder.css
- client/src/pages/LandingPage.js
- client/src/pages/Survey.js
[x] HOME PAGE -- "skip the search" in 3-box area -- make CF pink color
[x] NAV mobile -- no granny icon on mobile
[x] NAV -- make opaque/black
[x] NAV -- add rule left side / gray
[x] NAV -- move X to LEFT side of popover
[x] NAV -- mobile, move X left toward middle
[x] SURVEY -- delete top nav menu
[x] SURVEY INTRO -- thinner / centered text
[x] SURVEY BUTTONS -- make dark gray / pink on hover
[x] SURVEY PROGRESS BAR -- make CF pink
[x] SURVEY buttons -- make gray / click to pink (and stay pink upon selection)
[x] SURVEY -- Address entry -- put address 1, address 2, address 3  (One is required -- enter up to three addresses.)
[x] SURVEY -- address various spacing issues
[x] MAP SEARCH BOX -- make text BLACK (and home page, too).
[x] PROVIDER LANDING PAGE -- make whole page background …
> misc css and other stuff from micah
